# Generated by Django 2.2.17 on 2021-01-28 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210129_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTrack',
        ),
    ]
